name:                termviz
version:             0.1.0.0
synopsis:            Ascii terminal visualiser
#description:
homepage:            https://github.com/rumblesan/termviz#termviz
license:             BSD3
author:              Guy John
maintainer:          guy@rumblesan.com
copyright:           Guy John
category:            Art
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - file-embed
  - freetype2
  - GLFW-b
  - GLURaw
  - lens-simple
  - OpenGL
  - OpenGLRaw
  - optparse-applicative
  - stm
  - vector
  - Vec
  - yaml

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  termviz:
    source-dirs:      src
    main:             Main.hs
